version: 2
jobs:
  build:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    working_directory: ~/ci-test-api
    steps:
      - checkout
      - run: composer self-update
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - persist_to_workspace:
          root: .
          paths: .
  test:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    steps:
      - attach_workspace:
          at: ~/ci-test-api
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
