version: 2
jobs:
  test_unit:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    working_directory: ~/ci-test-api
    steps:
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit

  test_e2e:
    docker:
      - image: notnoopci/php:7.1.5-browsers
      - image: circleci/node:4
    working_directory: ~/ci-test-api
    steps:
      - checkout
      - run: composer install
      - run: php artisan serve
      - run: cd garden; npm install
      - run : cd garden; ./garden.js test

  deploy:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    steps:
      - run: echo "Deploying..."

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_unit
      - test_e2e
      - deploy:
          requires:
            - test_unit
            - test_e2e
          filters:
            branches:
              only: master
