version: 2
jobs:
  build:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    working_directory: ~/ci-test-api
    steps:
      - checkout
      - run: composer self-update
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - persist_to_workspace:
          root: .
          paths: .

  test:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    working_directory: ~/ci-test-api
    steps:
      - attach_workspace:
          at: ~/ci-test-api
      - run: ./vendor/bin/phpunit

  build_docker_image:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    working_directory: ~/ci-test-api
    steps:
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - setup_remote_docker
      - run: docker-compose build

  deploy:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    steps:
      - run: echo "Deploying..."

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build_docker_image:
          requires:
            - test
      - hold:
          type: approval
          requires:
            - build_docker_image
      - deploy:
          requires:
            - hold
